In [111]:
import matplotlib.pyplot as plt
%matplotlib inline

In [112]:
import IPython.display as ipd
import librosa
import librosa.display

In [113]:
!dir

bird_songs_metadata.csv  Untitled.ipynb  wavfiles


In [114]:
import pandas as pd
import os
import librosa

metadata=pd.read_csv('bird_songs_metadata.csv')
metadata.head(10)

id       genus   species subspecies           name  \
0  557838  Thryomanes  bewickii        NaN  Bewick's Wren   
1  557838  Thryomanes  bewickii        NaN  Bewick's Wren   
2  557838  Thryomanes  bewickii        NaN  Bewick's Wren   
3  557838  Thryomanes  bewickii        NaN  Bewick's Wren   
4  557838  Thryomanes  bewickii        NaN  Bewick's Wren   
5  557838  Thryomanes  bewickii        NaN  Bewick's Wren   
6  557838  Thryomanes  bewickii        NaN  Bewick's Wren   
7  557838  Thryomanes  bewickii        NaN  Bewick's Wren   
8  557838  Thryomanes  bewickii        NaN  Bewick's Wren   
9  557838  Thryomanes  bewickii        NaN  Bewick's Wren   

                recordist        country  \
0  Whitney Neufeld-Kaiser  United States   
1  Whitney Neufeld-Kaiser  United States   
2  Whitney Neufeld-Kaiser  United States   
3  Whitney Neufeld-Kaiser  United States   
4  Whitney Neufeld-Kaiser  United States   
5  Whitney Neufeld-Kaiser  United States   
6  Whitney Neufeld-Kaiser  United States   
7  Whitney Neufeld-Kaiser  United States   
8  Whitney Neufeld-Kaiser  United States   
9  Whitney Neufeld-Kaiser  United States   

                                  location  latitude  longitude altitude  \
0  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   
1  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   
2  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   
3  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   
4  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   
5  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   
6  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   
7  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   
8  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   
9  Arlington, Snohomish County, Washington   48.0708  -122.1006      100   

                   sound_type                   source_url  \
0  adult, sex uncertain, song  //www.xeno-canto.org/557838   
1  adult, sex uncertain, song  //www.xeno-canto.org/557838   
2  adult, sex uncertain, song  //www.xeno-canto.org/557838   
3  adult, sex uncertain, song  //www.xeno-canto.org/557838   
4  adult, sex uncertain, song  //www.xeno-canto.org/557838   
5  adult, sex uncertain, song  //www.xeno-canto.org/557838   
6  adult, sex uncertain, song  //www.xeno-canto.org/557838   
7  adult, sex uncertain, song  //www.xeno-canto.org/557838   
8  adult, sex uncertain, song  //www.xeno-canto.org/557838   
9  adult, sex uncertain, song  //www.xeno-canto.org/557838   

                                        license   time        date  \
0  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   
1  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   
2  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   
3  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   
4  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   
5  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   
6  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   
7  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   
8  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   
9  //creativecommons.org/licenses/by-nc-sa/4.0/  11:51  2020-03-14   

                                             remarks       filename  
0  Recorded with Voice Record Pro on iPhone7, nor...   557838-0.wav  
1  Recorded with Voice Record Pro on iPhone7, nor...   557838-1.wav  
2  Recorded with Voice Record Pro on iPhone7, nor...   557838-4.wav  
3  Recorded with Voice Record Pro on iPhone7, nor...   557838-5.wav  
4  Recorded with Voice Record Pro on iPhone7, nor...   557838-6.wav  
5  Recorded with Voice Record Pro on iPhone7, nor...   557838-8.wav  
6  Recorded with Voice Record Pro on iPhone7, nor...   557838-9.wav  

In [115]:
metadata['species'].value_counts()

melodia        1256
polyglottos    1182
cardinalis     1074
migratorius    1017
bewickii        893
Name: species, dtype: int64

In [116]:
audio_file = 'wavfiles/12996-6.wav'
y, sr = librosa.load(audio_file, sr=None)

# Get audio duration in seconds
duration = librosa.get_duration(y=y, sr=sr)

# Calculate number of frames
n_frames = int(sr * duration)

print(n_frames)
#66150

66150


In [117]:
def features_extractor(file):
    n_frames=120
    audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast') 
    mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=40)
    #++
    frames = np.array_split(mfccs_features.T, n_frames)
    features = np.concatenate(frames, axis=0)
    
    # Compute the mean of each feature across frames
    mean_features = np.mean(features, axis=0)                                
                                    
    
    return mean_features    

In [3]:
!dir

data  Untitled.ipynb


In [46]:
import numpy as np
from tqdm import tqdm
extracted_features=[]
for index_num,row in tqdm(metadata.iterrows()):
    file_name = os.path.join(os.path.abspath('wavfiles/'),row["filename"])                        
    final_class_labels=row["species"]
    data=features_extractor(file_name)
    extracted_features.append([data,final_class_labels])

5422it [03:39, 24.73it/s]


In [118]:
### converting extracted_features to Pandas dataframe
extracted_features_df=pd.DataFrame(extracted_features,columns=['feature','class'])
extracted_features_df.head()

feature     class
0  [-132.85225, 81.1399, 17.018225, 54.974297, -1...  bewickii
1  [-147.74393, 99.42544, 20.885643, 44.118813, 1...  bewickii
2  [-92.42778, 84.10635, 17.362778, 53.86046, -8....  bewickii
3  [-93.07557, 81.17431, 16.225544, 52.08842, -8....  bewickii
4  [-107.95914, 92.416, 17.773254, 43.13245, -1.8...  bewickii

In [119]:
### Split the dataset into independent and dependent dataset
X = np.array([f[0] for f in extracted_features])
y = np.array([f[1] for f in extracted_features])


In [120]:
X.shape

(5422, 40)

In [121]:
print(y)

['bewickii' 'bewickii' 'bewickii' ... 'cardinalis' 'cardinalis'
 'cardinalis']


In [122]:
# Reshape X to have a time dimension
n_frames = 120  # Replace this with the actual number of frames per audio clip
#X = X.reshape(X.shape[0], n_frames, X.shape[1])

# Convert y to one-hot encoding
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y = y.reshape(-1, 1)
enc = OneHotEncoder()
y = enc.fit_transform(y).toarray()


In [123]:
print(y)
print(y.shape)

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 ...
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
(5422, 5)


In [104]:
#from tensorflow.keras.utils import to_categorical
#from sklearn.preprocessing import LabelEncoder
#labelencoder=LabelEncoder()
#y=to_categorical(labelencoder.fit_transform(y))

In [124]:
### Train Test Split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [125]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [136]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout,Activation,Flatten
from tensorflow.keras.optimizers import Adam
import tensorflow.keras as keras
from sklearn import metrics
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [137]:
model = keras.Sequential()
model.add(keras.layers.LSTM(64, input_shape=(130,13), return_sequences=True))
model.add(keras.layers.LSTM(64))
model.add(keras.layers.Dense(64, activation='relu'))
model.add(keras.layers.Dropout(0.3))
model.add(keras.layers.Dense(10, activation='softmax'))

NotImplementedError: Cannot convert a symbolic Tensor (lstm_3/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

In [ ]:
model.summary()

In [ ]:
model.compile(loss='categorical_crossentropy',metrics=['accuracy'],optimizer='adam')

In [ ]:
def plot_history(history):
    """Plots accuracy/loss for training/validation set as a function of the epochs
        :param history: Training history of model
        :return:
    """

    fig, axs = plt.subplots(2)

    # create accuracy sublpot
    axs[0].plot(history.history["accuracy"], label="train accuracy")
    axs[0].plot(history.history["val_accuracy"], label="test accuracy")
    axs[0].set_ylabel("Accuracy")
    axs[0].legend(loc="lower right")
    axs[0].set_title("Accuracy eval")

    # create error sublpot
    axs[1].plot(history.history["loss"], label="train error")
    axs[1].plot(history.history["val_loss"], label="test error")
    axs[1].set_ylabel("Error")
    axs[1].set_xlabel("Epoch")
    axs[1].legend(loc="upper right")
    axs[1].set_title("Error eval")

    plt.show()

In [ ]:
## Trianing my model
from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime 

num_epochs = 100
num_batch_size = 32

checkpointer = ModelCheckpoint(filepath='saved_models/audio_classification.hdf5', 
                               verbose=1, save_best_only=True)
start = datetime.now()

history =model.fit(X_train, y_train, batch_size=num_batch_size, epochs=num_epochs, validation_data=(X_test, y_test), callbacks=[checkpointer], verbose=1)
plot_history(history)

duration = datetime.now() - start
print("Training completed in time: ", duration)

In [ ]:
test_accuracy=model.evaluate(X_test,y_test,verbose=0)
print(test_accuracy[1])